name: 01 - Building Blocks # key, values 

on: workflow_dispatch

# Nested object (dictionary) structure
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
        # Array of dictionaries
            - name: Successful step
              run: |
                echo "I will pass"
                exit 0
            - name: Say goodbye
              run: echo "Goodbye!"