name: 02 - Workflow Events

on: 
  push:
    branches:
      - main
  # pull_request:
  # schedule:
  #   - cron: '*/5 * * * *'
  # workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the OS
        run: |
          echo "I've been triggered by a(n) ${{github.event_name}} event."
          echo: "I am running on $RUNNER_OS"

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show the OS
        shell: bash
        run: |
          echo "I am running on a Windows runner"
          echo "I'm running on $RUNNER_OS"
